spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/toyzhiri
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  config:
    import: optional:classpath:application-local.yml


server:
  port: 8080

app:
  jwt:
    secret: key
    expiration-ms: 86400000