CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE user_role AS ENUM ('USER', 'PARTNER', 'ADMIN');

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    fullName VARCHAR(50) NOT NULL,
    phone VARCHAR(11) UNIQUE NOT NULL,
    role user_role NOT NULL DEFAULT 'USER',
    city VARCHAR(30) NOT NULL,
    emailVerified BOOLEAN NOT NULL DEFAULT FALSE,
    lastLogin TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);